name: inverse
channels:
  - conda-forge
dependencies:
  - python=3.12.5
  - pip=24.2
  - astra-toolbox=2.2.0
  - black=24.8.0
  - flake8=7.1.1
  - isort=5.13.2
  - mypy=1.11.2
  - pandas=2.2.2
  - pre-commit=3.8.0
  - pytest=8.3.2
  - pywavelets=1.7.0
  - scikit-image=0.23.2
  - scipy=1.13.1
  - tox=4.18.0
